replicaCount: 2

image:
  repository: ghcr.io/dheeman2912/spring-petclinic
  tag: "1.1"
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 1000
  runAsGroup: 3000

containerPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  port: 8080
  targetPort: 8080
  type: LoadBalancer
