apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: docker pull dheeman29/go-web-app:10244370821
        ports:
        - containerPort: 8080
      # imagePullSecrets:
      # - name: ghcr-secret
