apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-appp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-appp
  template:
    metadata:
      labels:
        app: my-appp
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
      containers:
      - name: my-appp
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

        image: ghcr.io/dheeman2912/spring-petclinic:1.1
        ports:
        - containerPort: 8080


