apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-security-context
spec:
  validationFailureAction: enforce
  rules:
    - name: check-security-context
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Pods must have a security context that specifies runAsUser and runAsGroup."
        pattern:
          spec:
            securityContext:
              runAsUser: 1000
              runAsGroup: 3000
