apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: attest-code-review
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: attest
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "ghcr.io/dheeman2912/*" 
          type: Cosign
          verifyDigest: true
          attestations:
            - type: https://example.com/CodeReview/v1
              attestors:
                - entries:
                    - keys:
                        publicKeys: |-
                          -----BEGIN PUBLIC KEY-----
                          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExtjNqfMhLnSKJWXQVpHnji/CK0/b
                          Lkd/9O1YBvu1XspKmcKvLZJJJYqkcy6VM6DN3rnJ0GhYC7ZcqvHvOUaHGw==
                          -----END PUBLIC KEY-----
              conditions:
                - all:
                    - key: "predicate.commit_id"
                      operator: Equals
                      value: "${COMMIT_ID}"
                    - key: "predicate.author_email"
                      operator: Equals
                      value: "dheemandass2912@gmail.com"
                    - key: "predicate.author_name"
                      operator: Equals
                      value: "DHEEMAN2912"  # Replace with the actual author name
                    - key: "predicate.branch"
                      operator: Equals
                      value: "test"
                    - key: "predicate.uri"
                      operator: Equals
                      value: "https://github.com/DHEEMAN2912/spring-petclinic"  # Replace with the actual URI







# apiVersion: kyverno.io/v1
# kind: ClusterPolicy
# metadata:
#   name: attest-code-review
# spec:
#   validationFailureAction: Enforce
#   background: false
#   webhookTimeoutSeconds: 30
#   failurePolicy: Fail
#   rules:
#     - name: attest
#       match:
#         any:
#           - resources:
#               kinds:
#                 - Pod
#       verifyImages:
#         - imageReferences:
#             - "*"
#           type: Cosign 
#           verifyDigest: true
#           attestations:
#             - type: https://example.com/CodeReview/v1
#               attestors:
#                 - entries:
#                     - keys:
#                         publicKeys: |-
#                           -----BEGIN PUBLIC KEY-----
#                           MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExtjNqfMhLnSKJWXQVpHnji/CK0/b
#                           Lkd/9O1YBvu1XspKmcKvLZJJJYqkcy6VM6DN3rnJ0GhYC7ZcqvHvOUaHGw==
#                           -----END PUBLIC KEY-----
#               conditions:
#                 - all:
#                     - key: "predicate.commit_id"
#                       operator: Equals
#                       value: "${COMMIT_ID}"



# apiVersion: kyverno.io/v1
# kind: ClusterPolicy
# metadata:
#   name: attest-code-review
# spec:
#   validationFailureAction: Audit  # Changed from Enforce to Audit
#   background: false
#   webhookTimeoutSeconds: 30
#   failurePolicy: Fail
#   rules:
#     - name: attest
#       match:
#         any:
#           - resources:
#               kinds:
#                 - Pod
#       verifyImages:
#         - imageReferences:
#             - "*"
#           type: Cosign 
#           verifyDigest: true
#           mutateDigest: false  # Added this line and set it to false
#           attestations:
#             - type: https://example.com/CodeReview/v1
#               attestors:
#                 - entries:
#                     - keys:
#                         publicKeys: |-
#                           -----BEGIN PUBLIC KEY-----
#                           MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExtjNqfMhLnSKJWXQVpHnji/CK0/b
#                           Lkd/9O1YBvu1XspKmcKvLZJJJYqkcy6VM6DN3rnJ0GhYC7ZcqvHvOUaHGw==
#                           -----END PUBLIC KEY-----
#               conditions:
#                 - all:
#                     - key: "predicate.commit_id"
#                       operator: Equals
#                       value: "${COMMIT_ID}"




# apiVersion: kyverno.io/v1
# kind: ClusterPolicy
# metadata:
#   name: enforce-predicate-attestation
# spec:
#   validationFailureAction: Enforce
#   rules:
#     - name: enforce-predicate-attestation
#       match:
#         any:
#           - resources:
#               kinds:
#                 - Pod
#       verifyImages:
#         - imageReferences:
#             - "ghcr.io/dheeman2912/spring-petclinic@sha256:*"
#           attestations:
#             - attestors:
#                 - entries:
#                     - keys:
#                         publicKeys: |
#                           -----BEGIN PUBLIC KEY-----
#                           MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExtjNqfMhLnSKJWXQVpHnji/CK0/b
#                           Lkd/9O1YBvu1XspKmcKvLZJJJYqkcy6VM6DN3rnJ0GhYC7ZcqvHvOUaHGw==
#                           -----END PUBLIC KEY-----
#                       signatureAlgorithm: sha256
#               conditions:
#                 - key: "predicate.type"
#                   operator: Equals
#                   value: "https://example.com/CodeReview/v1"
#               type: https://example.com/CodeReview/v1
#           required: true
#           mutateDigest: true


