# kyverno.yaml
name: Kyverno Policy Deployment

on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string

jobs:
  apply_kyverno_policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Apply Kyverno Policy
        env:
          CLUSTER_NAME: ${{ inputs.cluster_name }}
        run: |
          # Ensure Kubernetes context is set before applying policy
          kubectl config use-context $CLUSTER_NAME
          kubectl apply -f https://github.com/DHEEMAN2912/spring-petclinic/Kyverno/Kyverno-Policy.yaml
