name: DevSecOps Pipeline


on:
  push:
    branches:
      - Parameter
  pull_request:
  workflow_dispatch:
    inputs:
      azure_subscription:
        description: 'Azure Subscription'
        required: true
        type: string
      key_vault_name:
        description: 'Azure Key Vault Name'
        required: true
        type: string
      azure_resource_group:
        description: 'Azure Resource Group'
        required: true
        type: string
      secrets_filter:
        description: 'Secrets Filter (e.g., *)'
        required: false
        type: string

jobs:
  collect-metadata:
    uses: DHEEMAN2912/Reusable-Pipelines/.github/workflows/collect-metadata.yaml@main

  fetch-secret:
    needs: collect-metadata
    uses: DHEEMAN2912/Reusable-Pipelines/.github/workflows/Azure_Key_Vault.yaml@main
    with:
      azure_subscription: ${{ inputs.azure_subscription }}
      key_vault_name: ${{ inputs.key_vault_name }}
      azure_resource_group: ${{ inputs.azure_resource_group }}
      secrets_filter: ${{ inputs.secrets_filter }}
