name: DevSecOps Pipeline


on:
  push:
    branches:
      - Parameter
  pull_request:
  workflow_dispatch:
    

jobs:
  collect-metadata:
    uses: Reusable-Pipelines/.github/workflows/collect-metadata.yaml@main
