name: Call Template Workfloww
 
on:
  push:
    branches:
      - test
 
jobs:
  call-template:
    uses: dheeman2912/Template-Repo/.github/template1.yaml@main
    with:
      example_input: 'Hello from my-project!'
